export const types = {
    SET_USER: "SET_USER",
    LOG_OUT: "LOG_OUT",
    ADD_TO_MY_TEAM: "ADD_TO_MY_TEAM",
    ADD_USER_CRED: "ADD_USER_CRED",

    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",
    IS_USER_EXIST: "IS_USER_EXIST"
}

