export const types = {
    SET_USER: "SET_USER",
    LOG_OUT: "LOG_OUT",
    SET_MY_TEAM: "SET_MY_TEAM",
    ADD_USER_CRED: "ADD_USER_CRED",
    FETCH_INFO_USER: "FETCH_INFO_USER",

    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",
    HAS_PROFILE: "HAS_PROFILE",
    SET_USER_CRED: "SET_USER_CRED",

    FETCH_INFO_TEAM: "FETCH_INFO_TEAM",
    // if you logout and login immediately;reset the redux state;show what happens if you don't do it
    RESET_TEAM_STATE: "RESET_TEAM_STATE",
    SET_SEARCHED_RESULTS: "SET_SEARCH_RESULTS",

    SET_LAST_AND_NEXT_FIXTURES: "SET_LAST_AND_NEXT_FIXTURES",
    SET_CURRENT_OR_LAST_FIXTURE_ID: "SET_CURRENT_OR_LAST_FIXTURE_ID",

    SET_FIXTURE_DETAILS: "SET_FIXTURE_DETAILS",
    SET_HEAD_TO_HEAD: "SET_HEAD_TO_HEAD",
    SET_PREDICTION: "SET_PREDICTION",

    SET_DOMESTIC_LEAGUE_ID: "SET_DOMESTIC_LEAGUE_ID",
    SET_TOP_PLAYERS: "SET_TOP_PLAYERS",
    SET_DOMESTIC_LEAGUE_TABLE: "SET_DOMESTIC_LEAGUE_TABLE",

    SET_API_STATUS: "SET_API_STATUS"

}

