export const types = {
    SET_USER: "SET_USER",
    LOG_OUT: "LOG_OUT",
    ADD_TO_MY_TEAM: "ADD_TO_MY_TEAM",
    ADD_USER_CRED: "ADD_USER_CRED",

    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",
    IS_USER_EXIST: "IS_USER_EXIST",

    ADD_TO_LAST_AND_NEXT_FIXTURES: "ADD_TO_LAST_AND_NEXT_FIXTURES",
    ADD_TO_CURRENT_OR_LAST_FIXTURE_ID: "ADD_TO_CURRENT_OR_LAST_FIXTURE_ID",

    ADD_TO_FIXTURE_DETAILS: "ADD_TO_FIXTURE_DETAILS",
    ADD_TO_HEAD_TO_HEAD: "ADD_TO_HEAD_TO_HEAD",
    ADD_PREDICTION: "ADD_PREDICTION",

    SET_DOMESTIC_LEAGUE_ID: "SET_DOMESTIC_LEAGUE_ID",
    SET_TOP_PLAYERS: "SET_TOP_PLAYERS",
    SET_DOMESTIC_LEAGUE_TABLE: "SET_DOMESTIC_LEAGUE_TABLE"
}
//TODO change ADD to SET

